const STORAGE_KEY = 'harborview-signage-content';
const DEFAULT_CONTENT = {
  organization: 'Harborview Care',
  location: 'Main reception',
  policy: { title: 'Respectful communication', text: 'Speak with patience, listen fully, and make every person feel heard.', owner: 'People & Culture' },
  celebration: { title: 'Celebrating our care team', text: 'Thank you to every colleague making a difference this week.', date: 'Friday 21 August' },
  audit: { score: '94%', label: 'Quality audit', detail: 'All critical actions closed this month.' },
  photo: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85',
  weather: '21°',
  city: 'London',
  ticker: 'Welcome to Harborview Care  •  Please check in at reception  •  Have a wonderful day',
  layoutColumns: 2,
  sections: [
    { type: 'policy', title: 'Policy of the week', text: 'Respectful communication', detail: 'Speak with patience, listen fully, and make every person feel heard.' },
    { type: 'image', title: 'Featured image', text: 'People make the place.', detail: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85' }
  ]
};

let content = loadContent();
let wakeLock;
const app = document.querySelector('#app');

function loadContent() {
  try {
    const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
    return { ...DEFAULT_CONTENT, ...stored, sections: stored.sections?.length ? stored.sections : DEFAULT_CONTENT.sections };
  }
  catch { return DEFAULT_CONTENT; }
}
function saveContent() { localStorage.setItem(STORAGE_KEY, JSON.stringify(content)); }
function escapeHtml(value = '') { return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
function navigate(path) { location.hash = path; }
function icon(name) { return { grid: '▦', play: '▶', image: '▧', shield: '◇', users: '♧', gear: '⚙', clock: '◷', weather: '☼', check: '✓', logout: '↪', menu: '☰' }[name] || '•'; }

function loginView() {
  app.innerHTML = `<section class="login-shell"><div class="login-art"><div class="brand-mark">H</div><p class="eyebrow">DIGITAL SIGNAGE PLATFORM</p><h1>Make every screen<br><em>feel alive.</em></h1><p class="muted">Publish thoughtful updates to every display across your site, from one calm control room.</p><div class="login-art-footer"><span>● Systems online</span><span>Last sync 2 min ago</span></div></div><form class="login-form" id="login-form"><p class="eyebrow">WELCOME BACK</p><h2>Sign in to your studio</h2><p class="muted">Manage screens, content and schedules.</p><label>Email<input name="email" type="email" value="admin@harborview.local" required></label><label>Password<input name="password" type="password" value="admin123" required></label><button class="button button-dark" type="submit">Open studio <span>→</span></button><p class="login-hint">Demo access: admin@harborview.local / admin123</p></form></section>`;
  document.querySelector('#login-form').onsubmit = event => { event.preventDefault(); navigate('/admin'); };
}

function shell(active, body) {
  app.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="logo"><span class="brand-mark small">H</span><span>harborview<span class="logo-dot">.</span></span></div><div class="site-switcher"><span class="status-dot"></span><div><strong>${escapeHtml(content.location)}</strong><small>All screens online</small></div><span>⌄</span></div><nav><a class="${active === 'overview' ? 'active' : ''}" href="#/admin">${icon('grid')} Overview</a><a class="${active === 'content' ? 'active' : ''}" href="#/admin/content">${icon('image')} Content library</a><a class="${active === 'screens' ? 'active' : ''}" href="#/admin/screens">${icon('play')} Screens & playlists</a><a class="${active === 'reports' ? 'active' : ''}" href="#/admin/reports">${icon('shield')} Audit results</a></nav><div class="sidebar-bottom"><a href="#/player" target="_blank">${icon('play')} Open TV player</a><a href="#/login">${icon('logout')} Sign out</a><div class="profile"><span class="avatar">AM</span><span><strong>Alex Morgan</strong><small>Administrator</small></span><span>•••</span></div></div></aside><section class="main-content">${body}</section></div>`;
}

function topbar(kicker, title, action = '') { return `<header class="topbar"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1></div>${action}</header>`; }
function overviewView() {
  shell('overview', `${topbar('WEDNESDAY, 19 AUGUST 2026', 'Good morning, Alex.', '<a class="button button-dark" href="#/admin/content">+ Add content</a>')}<div class="hero-row"><div class="welcome-panel"><div><p class="eyebrow">THIS WEEK AT A GLANCE</p><h2>A little clarity<br>goes a long way.</h2><p class="muted">Your displays are telling a good story today.</p></div><div class="sunburst">✦</div></div><div class="stat-panel"><span class="stat-icon green">${icon('play')}</span><strong>04</strong><span>Active screens</span><small><b>All healthy</b> · synced 2 min ago</small></div><div class="stat-panel"><span class="stat-icon orange">${icon('image')}</span><strong>12</strong><span>Live items</span><small><b>+3 this week</b> · across 4 playlists</small></div></div><div class="section-heading"><div><p class="eyebrow">CONTENT PULSE</p><h2>What’s on your screens</h2></div><a href="#/admin/content">View library →</a></div><div class="content-grid"><article class="feature-card photo-card" style="background-image:url('${escapeHtml(content.photo)}')"><div class="overlay"><span class="tag">FEATURED IMAGE</span><h3>People make<br>the place.</h3><span>Showing on 4 screens · until Sunday</span></div></article><article class="feature-card policy-card"><span class="tag tag-cream">POLICY OF THE WEEK</span><h3>${escapeHtml(content.policy.title)}</h3><p>${escapeHtml(content.policy.text)}</p><div class="card-footer"><span>${escapeHtml(content.policy.owner)}</span><span>↗</span></div></article><article class="feature-card celebration-card"><span class="tag tag-cream">CELEBRATION</span><h3>${escapeHtml(content.celebration.title)}</h3><p>${escapeHtml(content.celebration.text)}</p><div class="card-footer"><span>${escapeHtml(content.celebration.date)}</span><span>✦</span></div></article></div><div class="lower-grid"><div><div class="section-heading compact"><div><p class="eyebrow">SCREEN HEALTH</p><h2>Live now</h2></div><a href="#/admin/screens">Manage screens →</a></div><div class="screen-list"><div class="screen-line"><span class="screen-thumb reception"></span><strong>Reception display</strong><span class="screen-location">Main entrance</span><span class="online"><i></i> Online</span><span>•••</span></div><div class="screen-line"><span class="screen-thumb lounge"></span><strong>Staff lounge</strong><span class="screen-location">First floor</span><span class="online"><i></i> Online</span><span>•••</span></div></div></div><article class="audit-summary"><div class="audit-ring"><strong>${escapeHtml(content.audit.score)}</strong><span>pass</span></div><div><p class="eyebrow">LATEST AUDIT</p><h3>${escapeHtml(content.audit.label)}</h3><p>${escapeHtml(content.audit.detail)}</p><a href="#/admin/reports">Open report →</a></div></article></div>`);
}
function sectionEditor(section, index) {
  const options = ['text', 'policy', 'image', 'pdf', 'qr', 'clock', 'weather', 'audit'].map(type => `<option value="${type}" ${section.type === type ? 'selected' : ''}>${type.toUpperCase()}</option>`).join('');
  return `<div class="section-editor" data-section="${index}"><div class="section-editor-head"><strong>Section ${index + 1}</strong><button type="button" class="remove-section" data-index="${index}">Remove</button></div><label>Display type<select name="sectionType">${options}</select></label><label>Heading<input name="sectionTitle" value="${escapeHtml(section.title || '')}"></label><label>Message or label<textarea name="sectionText">${escapeHtml(section.text || '')}</textarea></label><label>Image, PDF, or link URL<input name="sectionDetail" value="${escapeHtml(section.detail || '')}" placeholder="https://..."></label></div>`;
}
function contentView() {
  shell('content', `${topbar('CONTENT LIBRARY', 'Your content studio', '<button class="button button-dark" id="save-content">Save changes</button>')}<div class="editor-grid"><form class="editor-panel" id="content-form"><p class="eyebrow">EDIT SCREEN SECTIONS</p><h2>Compose your display.</h2><p class="muted">Add up to four sections. They will share the screen equally.</p><label>Screen layout<select name="layoutColumns"><option value="1" ${content.layoutColumns === 1 ? 'selected' : ''}>1 section · full screen</option><option value="2" ${content.layoutColumns === 2 ? 'selected' : ''}>2 sections · equal split</option><option value="3" ${content.layoutColumns === 3 ? 'selected' : ''}>3 sections · equal split</option><option value="4" ${content.layoutColumns === 4 ? 'selected' : ''}>4 sections · equal split</option></select></label><div id="section-editors">${content.sections.map(sectionEditor).join('')}</div><button type="button" class="button button-outline add-section" id="add-section">+ Add display section</button><label>Bottom ticker<textarea name="ticker">${escapeHtml(content.ticker)}</textarea></label></form><div><div class="preview-label"><span class="eyebrow">LIVE PREVIEW</span><a href="#/player" target="_blank">Open full player ↗</a></div><div class="mini-player">${playerMarkup(true)}</div></div></div>`);
  const form = document.querySelector('#content-form');
  document.querySelector('#add-section').onclick = () => { if (content.sections.length < 4) { content.sections.push({ type: 'text', title: 'New section', text: 'Add a message here.', detail: '' }); document.querySelector('#section-editors').insertAdjacentHTML('beforeend', sectionEditor(content.sections.at(-1), content.sections.length - 1)); bindSectionButtons(); } };
  const bindSectionButtons = () => document.querySelectorAll('.remove-section').forEach(button => button.onclick = () => { if (document.querySelectorAll('.section-editor').length > 1) { button.closest('.section-editor').remove(); } });
  bindSectionButtons();
  document.querySelector('#save-content').onclick = () => { const data = new FormData(form); content.layoutColumns = Number(data.get('layoutColumns')); content.ticker = data.get('ticker'); content.sections = [...form.querySelectorAll('.section-editor')].map(editor => ({ type: editor.querySelector('[name="sectionType"]').value, title: editor.querySelector('[name="sectionTitle"]').value, text: editor.querySelector('[name="sectionText"]').value, detail: editor.querySelector('[name="sectionDetail"]').value })); content.photo = content.sections.find(section => section.type === 'image')?.detail || content.photo; saveContent(); document.querySelector('#save-content').textContent = 'Saved ✓'; document.querySelector('.mini-player').innerHTML = playerMarkup(true); setTimeout(() => document.querySelector('#save-content').textContent = 'Save changes', 1400); };
}
function screensView() { shell('screens', `${topbar('SCREENS & PLAYLISTS', 'Every screen, in sync.', '<button class="button button-dark" id="kiosk">Launch kiosk mode</button>')}<div class="screen-management"><div class="playlist-card"><span class="tag">DEFAULT PLAYLIST</span><h2>Welcome loop</h2><p>5 items · runs continuously · 10 second intervals</p><div class="playlist-items"><div><b>01</b><span class="item-color teal"></span><strong>Policy of the week</strong><small>10 sec</small></div><div><b>02</b><span class="item-color coral"></span><strong>Celebration</strong><small>10 sec</small></div><div><b>03</b><span class="item-color gold"></span><strong>Audit results</strong><small>10 sec</small></div></div></div><div class="screen-setup"><p class="eyebrow">PLAYER SETTINGS</p><h2>Kiosk-ready by design.</h2><label class="toggle-row"><span><strong>Hide cursor & controls</strong><small>Keep the display presentation-ready</small></span><input type="checkbox" checked></label><label class="toggle-row"><span><strong>Prevent screen sleep</strong><small>Uses Wake Lock when supported</small></span><input type="checkbox" checked></label><label class="toggle-row"><span><strong>Auto-start player</strong><small>Recommended for Android TV launcher</small></span><input type="checkbox" checked></label></div></div>`); document.querySelector('#kiosk').onclick = () => navigate('/player?kiosk=1'); }
function reportsView() { shell('reports', `${topbar('AUDIT RESULTS', 'Quality at a glance.', '<button class="button button-outline">Export report ↓</button>')}<div class="report-hero"><div><span class="tag tag-cream">AUGUST 2026</span><h2>Strong work, with<br>room to grow.</h2><p>Latest site audit across 18 checks.</p></div><div class="big-score">${escapeHtml(content.audit.score)}<small>overall pass rate</small></div></div><div class="report-table"><div class="table-head"><span>AREA</span><span>RESULT</span><span>OWNER</span><span>UPDATED</span></div><div><strong>Environment & safety</strong><span class="pass">✓ Passed</span><span>Facilities</span><span>18 Aug 2026</span></div><div><strong>Care documentation</strong><span class="pass">✓ Passed</span><span>Clinical team</span><span>15 Aug 2026</span></div><div><strong>Training compliance</strong><span class="review">! Review</span><span>People & Culture</span><span>12 Aug 2026</span></div></div>`); }

function sectionMarkup(section) { const type = section.type; if (type === 'image') return `<article class="display-section section-image" style="background-image:url('${escapeHtml(section.detail || content.photo)}')"><span class="tag tag-cream">IMAGE</span><h2>${escapeHtml(section.text || section.title)}</h2></article>`; if (type === 'pdf' || type === 'qr') { const link = section.detail || '#'; return `<article class="display-section section-document"><span class="tag tag-cream">${type === 'pdf' ? 'PDF DOCUMENT' : 'SCAN QR CODE'}</span><h2>${escapeHtml(section.title)}</h2><p>${escapeHtml(section.text)}</p>${type === 'qr' ? `<img class="qr-code" src="https://api.qrserver.com/v1/create-qr-code/?size=240x240&data=${encodeURIComponent(link)}" alt="QR code">` : ''}<a class="document-link" href="${escapeHtml(link)}" target="_blank">${type === 'pdf' ? 'Open PDF ↗' : 'Open link ↗'}</a></article>`; } if (type === 'clock') return `<article class="display-section section-clock"><span class="tag tag-cream">TIME</span><strong class="large-clock live-clock">--:--</strong><p>${escapeHtml(section.text || 'Have a wonderful day')}</p></article>`; if (type === 'weather') return `<article class="display-section section-weather"><span class="tag tag-cream">WEATHER · ${escapeHtml(content.city)}</span><strong>${escapeHtml(content.weather)}</strong><p>${escapeHtml(section.text || 'Clear skies today')}</p></article>`; if (type === 'audit') return `<article class="display-section section-audit"><span class="tag tag-cream">AUDIT RESULT</span><strong>${escapeHtml(content.audit.score)}</strong><h2>${escapeHtml(section.title || content.audit.label)}</h2><p>${escapeHtml(section.text || content.audit.detail)}</p></article>`; return `<article class="display-section section-text"><span class="tag tag-cream">${escapeHtml(section.title || 'MESSAGE')}</span><h2>${escapeHtml(section.text || '')}</h2><p>${escapeHtml(section.detail || '')}</p></article>`; }
function playerMarkup(mini = false) { return `<div class="player-scene ${mini ? 'mini' : ''}"><div class="player-top"><span class="logo light">harborview<span class="logo-dot">.</span></span><span>${escapeHtml(content.city)} · <b class="live-clock">--:--</b></span></div><main class="display-grid columns-${Math.min(4, Math.max(1, content.layoutColumns || content.sections.length))}">${content.sections.slice(0, 4).map(sectionMarkup).join('')}</main><div class="player-bottom"><span>☼ ${escapeHtml(content.weather)} · Clear</span><span>${escapeHtml(content.ticker)}</span></div></div>`; }
function playerView() { document.body.classList.add('player-mode'); app.innerHTML = playerMarkup(); const updateClock = () => document.querySelectorAll('.live-clock').forEach(el => el.textContent = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })); updateClock(); setInterval(updateClock, 1000); document.documentElement.requestFullscreen?.().catch(() => {}); navigator.wakeLock?.request('screen').then(lock => wakeLock = lock).catch(() => {}); }
function render() { document.body.classList.remove('player-mode'); const path = location.hash || '#/login'; if (path.startsWith('#/player')) playerView(); else if (path === '#/admin/content') contentView(); else if (path === '#/admin/screens') screensView(); else if (path === '#/admin/reports') reportsView(); else if (path === '#/admin') overviewView(); else loginView(); }
window.addEventListener('hashchange', render); render();
if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(() => {});
